CREATE DATABASE MEDICAPS;

USE MEDICAPS;

CREATE TABLE FACULTY(FID CHAR(10) PRIMARY KEY, FNAME VARCHAR(50) NOT NULL);

INSERT INTO FACULTY VALUES
('F01','Engineering'),
('F02','Management Studies'),
('F03','Commerce'),
('F04','Agriculture'),
('F05','Science'),
('F06','Arts and Humanities'),
('F07','Pharmacy'),
('F08','Law');

CREATE TABLE DEPT(FID CHAR(10) NOT NULL,DEPTID CHAR(10) PRIMARY KEY,DEPTNAME VARCHAR(50) NOT NULL,FOREIGN KEY(FID) REFERENCES FACULTY(FID));

INSERT INTO DEPT VALUES
('F01','D01','COMPUTER SCIENCE AND ENGINEERING'),
('F01','D02','INFORMATION TECHNOLOGY'),
('F01','D03','MECHANICAL ENGINEERING'),
('F01','D04','ELECTRONICS ENGINEERING'),
('F01','D05','CIVIL ENGINEERING'),
('F01','D06','ELECTRICAL ENGINEERING'),
('F01','D07','COMPUTER APPLICATION'),
('F02','D08','MANAGEMENT'),
('F03','D09','COMMERCE'),
('F04','D10','AGRICULTURE'),
('F05','D11','PHYSICS'),
('F05','D12','CHEMISTRY'),
('F05','D13','MATHEMATICS'),
('F05','D14','COMPUTER SCIENCE'),
('F05','D15','FORENSIC SCIENCE'),
('F05','D16','BIOTECHNOLOGY'),
('F07','D17','PHARMACY'),
('F06','D18','LANGUAGE'),
('F08','D19','LAW');

CREATE TABLE EMPLOYEE (FID CHAR(10), DEPTID CHAR(10),EMPID CHAR(10) PRIMARY KEY,EMPNAME VARCHAR(50) NOT NULL,DESIGNATION VARCHAR(50) NOT NULL,PASSWORD VARCHAR(50) NOT NULL,EMAIL VARCHAR(50) UNIQUE NOT NULL,MOBILENO BIGINT UNIQUE NOT NULL,FOREIGN KEY(FID) REFERENCES FACULTY(FID),FOREIGN KEY(DEPTID) REFERENCES DEPT(DEPTID));

INSERT INTO EMPLOYEE VALUES
('F01','D01','E01','A','ASSISTANT PROFESSOR','1','A@XYZ.COM',1234567890);


CREATE TABLE NOTESHEET(NOTEID INTEGER PRIMARY KEY AUTO_INCREMENT,FID CHAR(10),DEPTID CHAR(10),EMPID CHAR(10),SUBJECT VARCHAR(4000) NOT NULL,DETAILS VARCHAR(4000) NOT NULL,DATE DATE NOT NULL,TIME TIME NOT NULL,STATUS INTEGER,FOREIGN KEY(FID) REFERENCES FACULTY(FID),FOREIGN KEY(DEPTID) REFERENCES DEPT(DEPTID),FOREIGN KEY(EMPID) REFERENCES EMPLOYEE(EMPID));

INSERT INTO NOTESHEET(FID,DEPTID,EMPID,SUBJECT,DETAILS,DATE,TIME,STATUS) VALUES('F01','D01','E01','DUMMY1','DUMMY',CURDATE(),CURTIME(),1);


CREATE TABLE NOTESTATUS(SNO INTEGER PRIMARY KEY AUTO_INCREMENT,NOTEID INTEGER NOT NULL,EMPID CHAR(10),COMMENT VARCHAR(1000),STATUS INTEGER,DATE DATE,TIME TIME, FOREIGN KEY(EMPID) REFERENCES EMPLOYEE(EMPID));

INSERT INTO NOTESTATUS(NOTEID,EMPID,COMMENT,STATUS,DATE,TIME) VALUES(1,'E05','HELLO USER',1,CURDATE(),CURTIME());

CREATE TABLE ADMIN(ADMINID CHAR(10) PRIMARY KEY,PASSWORD VARCHAR(50) NOT NULL,EMPNAME VARCHAR(50) NOT NULL,EMAIL VARCHAR(50) UNIQUE NOT NULL,MOBILENO BIGINT  UNIQUE NOT NULL,DESIGNATION VARCHAR(50) NOT NULL);

INSERT INTO ADMIN VALUES('admin',"6969","Yuvraj Singh Jat","admin@medicaps.ac.in","9843256732",'ADMIN HEAD');